// next-frontend/src/app/fund-history/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { FundHistoryData } from '../../types/fund';
import { fundService } from '../../services/fundService';
import {
  Box,
  Card,
  CardContent,
  CardHeader,
  Typography,
  TextField,
  Button,
  IconButton,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  CircularProgress,
  Divider,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Snackbar,
  Alert,
  Chip,
  Tabs,
  Tab,
  CardActions
} from '@mui/material';
import {
  Search as SearchIcon,
  Refresh as RefreshIcon,
  Download as DownloadIcon,
  BarChart as BarChartIcon,
  ShowChart as LineChartIcon,
  AccountBalanceWallet as AccountBalanceWalletIcon
} from '@mui/icons-material';
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts';

const FundHistoryPage: React.FC = () => {
  // 表单状态
  const [fundCode, setFundCode] = useState<string>('110022');
  const [startDate, setStartDate] = useState<string>(() => {
    const date = new Date();
    date.setFullYear(date.getFullYear() - 1);
    return date.toISOString().split('T')[0];
  });
  const [endDate, setEndDate] = useState<string>(new Date().toISOString().split('T')[0]);
  const [chartType, setChartType] = useState<'line' | 'bar'>('line');
  const [timePeriod, setTimePeriod] = useState<string>('1y');
  
  // 数据状态
  const [historyData, setHistoryData] = useState<FundHistoryData[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isChartLoading, setIsChartLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  
  // 时间周期选项
  const timePeriods = [
    { value: '7d', label: '最近7天' },
    { value: '1m', label: '最近1个月' },
    { value: '3m', label: '最近3个月' },
    { value: '6m', label: '最近6个月' },
    { value: '1y', label: '最近1年' },
    { value: '3y', label: '最近3年' },
    { value: '5y', label: '最近5年' },
    { value: 'custom', label: '自定义' }
  ];

  // 根据时间周期更新日期范围
  useEffect(() => {
    if (timePeriod !== 'custom') {
      const end = new Date();
      const start = new Date();
      
      switch (timePeriod) {
        case '7d':
          start.setDate(end.getDate() - 7);
          break;
        case '1m':
          start.setMonth(end.getMonth() - 1);
          break;
        case '3m':
          start.setMonth(end.getMonth() - 3);
          break;
        case '6m':
          start.setMonth(end.getMonth() - 6);
          break;
        case '1y':
          start.setFullYear(end.getFullYear() - 1);
          break;
        case '3y':
          start.setFullYear(end.getFullYear() - 3);
          break;
        case '5y':
          start.setFullYear(end.getFullYear() - 5);
          break;
      }
      
      setStartDate(start.toISOString().split('T')[0]);
      setEndDate(end.toISOString().split('T')[0]);
    }
  }, [timePeriod]);

  // 获取历史净值数据
  const fetchHistoryData = async () => {
    setIsLoading(true);
    setIsChartLoading(true);
    setError(null);
    
    try {
      const data = await fundService.getFundNavFromEastmoney(fundCode, 1, 1000, startDate, endDate);
      setHistoryData(data);
      setSuccessMessage(`成功加载基金${fundCode}的历史净值数据`);
    } catch (err) {
      setError('获取基金历史数据失败，请检查基金代码或网络连接');
      console.error('获取基金历史数据失败:', err);
    } finally {
      setIsLoading(false);
      setIsChartLoading(false);
    }
  };

  // 刷新数据
  const refreshData = () => {
    // 清除缓存
    fundService.clearNavDataCache(fundCode);
    // 重新加载数据
    fetchHistoryData();
  };

  // 导出数据
  const exportData = () => {
    if (historyData.length === 0) {
      setError('没有数据可以导出');
      return;
    }
    
    // 生成CSV内容
    const headers = ['日期', '单位净值', '累计净值', '日涨跌幅(%)'];
    const rows = historyData.map(item => [
      item.date,
      item.nav,
      item.totalNav,
      (item.dailyChange * 100).toFixed(2)
    ]);
    
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');
    
    // 创建下载链接
    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    
    link.setAttribute('href', url);
    link.setAttribute('download', `fund_history_${fundCode}_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    setSuccessMessage('数据导出成功');
  };

  // 格式化涨跌幅
  const formatDailyChange = (value: number): string => {
    const sign = value > 0 ? '+' : '';
    return `${sign}${(value * 100).toFixed(2)}%`;
  };

  // 获取涨跌幅样式
  const getDailyChangeClass = (value: number): string => {
    if (value > 0) return 'positive';
    if (value < 0) return 'negative';
    return 'neutral';
  };

  // 渲染图表
  const renderChart = () => {
    if (historyData.length === 0) {
      return (
        <Box sx={{ height: 400, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'text.secondary' }}>
          <Typography variant="h6">暂无数据，无法生成图表</Typography>
        </Box>
      );
    }

    return (
      <ResponsiveContainer width="100%" height={400}>
        {chartType === 'line' ? (
          <LineChart data={historyData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis 
              dataKey="date" 
              tick={{ fontSize: 12 }}
              tickFormatter={(value) => value.slice(5)} // 只显示月-日
            />
            <YAxis 
              tick={{ fontSize: 12 }}
              tickFormatter={(value) => value.toFixed(3)}
              domain={['auto', 'auto']}
            />
            <Tooltip 
              formatter={(value: number) => [value.toFixed(4), '']}
              labelFormatter={(label) => `日期: ${label}`}
            />
            <Legend />
            <Line 
              type="monotone" 
              dataKey="nav" 
              name="单位净值" 
              stroke="#3f51b5" 
              strokeWidth={2}
              dot={{ r: 2 }}
              activeDot={{ r: 5 }}
            />
            <Line 
              type="monotone" 
              dataKey="totalNav" 
              name="累计净值" 
              stroke="#4caf50" 
              strokeWidth={2}
              dot={{ r: 2 }}
              activeDot={{ r: 5 }}
            />
          </LineChart>
        ) : (
          <BarChart data={historyData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis 
              dataKey="date" 
              tick={{ fontSize: 12 }}
              tickFormatter={(value) => value.slice(5)} // 只显示月-日
            />
            <YAxis 
              tick={{ fontSize: 12 }}
              tickFormatter={(value) => value.toFixed(3)}
            />
            <Tooltip 
              formatter={(value: number) => [value.toFixed(4), '']}
              labelFormatter={(label) => `日期: ${label}`}
            />
            <Legend />
            <Bar 
              dataKey="nav" 
              name="单位净值" 
              fill="#3f51b5" 
            />
            <Bar 
              dataKey="totalNav" 
              name="累计净值" 
              fill="#4caf50" 
            />
          </BarChart>
        )}
      </ResponsiveContainer>
    );
  };

  return (
    <Box sx={{ maxWidth: 1200, margin: '0 auto' }}>
      {/* 页面标题 */}
      <Typography variant="h4" component="h1" gutterBottom sx={{ fontWeight: 600, display: 'flex', alignItems: 'center', gap: 1 }}>
        <AccountBalanceWalletIcon sx={{ fontSize: 32 }} />
        基金历史净值查询
      </Typography>
      <Divider sx={{ mb: 3 }} />

      {/* 查询表单 */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 2, alignItems: 'end' }}>
            {/* 基金代码输入 */}
            <TextField
              label="基金代码"
              variant="outlined"
              value={fundCode}
              onChange={(e) => setFundCode(e.target.value)}
              size="small"
              sx={{ flex: 1, minWidth: 200 }}
              placeholder="请输入基金代码，例如：110022"
            />
            
            {/* 时间周期选择 */}
            <FormControl size="small" sx={{ minWidth: 150 }}>
              <InputLabel>时间周期</InputLabel>
              <Select
                value={timePeriod}
                label="时间周期"
                onChange={(e) => setTimePeriod(e.target.value)}
              >
                {timePeriods.map((period) => (
                  <MenuItem key={period.value} value={period.value}>
                    {period.label}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
            
            {/* 开始日期 */}
            <TextField
              label="开始日期"
              type="date"
              variant="outlined"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              size="small"
              sx={{ minWidth: 150 }}
              InputLabelProps={{ shrink: true }}
            />
            
            {/* 结束日期 */}
            <TextField
              label="结束日期"
              type="date"
              variant="outlined"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              size="small"
              sx={{ minWidth: 150 }}
              InputLabelProps={{ shrink: true }}
            />
            
            {/* 查询按钮 */}
            <Button
              variant="contained"
              startIcon={<SearchIcon />}
              onClick={fetchHistoryData}
              disabled={isLoading}
              size="small"
            >
              {isLoading ? <CircularProgress size={20} /> : '查询'}
            </Button>
            
            {/* 刷新按钮 */}
            <IconButton
              color="secondary"
              onClick={refreshData}
              disabled={isLoading}
              title="刷新数据"
            >
              <RefreshIcon />
            </IconButton>
            
            {/* 导出按钮 */}
            <IconButton
              color="secondary"
              onClick={exportData}
              disabled={isLoading || historyData.length === 0}
              title="导出数据"
            >
              <DownloadIcon />
            </IconButton>
          </Box>
        </CardContent>
      </Card>

      {/* 图表区域 */}
      <Card sx={{ mb: 3 }}>
        <CardHeader
          title="净值走势图表"
          subheader="基金单位净值和累计净值变化趋势"
          action={
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <Typography variant="body2" sx={{ color: 'text.secondary' }}>图表类型:</Typography>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <Chip
                  label="折线图"
                  icon={<LineChartIcon fontSize="small" />}
                  color={chartType === 'line' ? 'primary' : 'default'}
                  onClick={() => setChartType('line')}
                  clickable
                />
                <Chip
                  label="柱状图"
                  icon={<BarChartIcon fontSize="small" />}
                  color={chartType === 'bar' ? 'primary' : 'default'}
                  onClick={() => setChartType('bar')}
                  clickable
                />
              </Box>
            </Box>
          }
        />
        <CardContent>
          {isChartLoading ? (
            <Box sx={{ height: 400, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <CircularProgress />
            </Box>
          ) : (
            renderChart()
          )}
        </CardContent>
      </Card>

      {/* 数据表格 */}
      <Card>
        <CardHeader
          title="历史净值数据"
          subheader={`共 ${historyData.length} 条记录`}
        />
        <CardContent>
          {isLoading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
              <CircularProgress />
            </Box>
          ) : historyData.length === 0 ? (
            <Box sx={{ textAlign: 'center', py: 4, color: 'text.secondary' }}>
              <Typography variant="h6">暂无数据</Typography>
              <Typography variant="body2">请输入基金代码并点击查询按钮获取数据</Typography>
            </Box>
          ) : (
            <TableContainer component={Paper} sx={{ maxHeight: 600 }}>
              <Table stickyHeader aria-label="fund history table">
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600 }}>日期</TableCell>
                    <TableCell sx={{ fontWeight: 600 }}>单位净值</TableCell>
                    <TableCell sx={{ fontWeight: 600 }}>累计净值</TableCell>
                    <TableCell sx={{ fontWeight: 600 }}>日涨跌幅</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {historyData.map((row) => (
                    <TableRow
                      key={row.date}
                      sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                    >
                      <TableCell>{row.date}</TableCell>
                      <TableCell>{row.nav.toFixed(4)}</TableCell>
                      <TableCell>{row.totalNav.toFixed(4)}</TableCell>
                      <TableCell
                        sx={{
                          fontWeight: 500,
                          color: row.dailyChange > 0 ? '#4caf50' : row.dailyChange < 0 ? '#f44336' : '#9e9e9e'
                        }}
                      >
                        {formatDailyChange(row.dailyChange)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
        {historyData.length > 0 && (
          <CardActions sx={{ justifyContent: 'flex-end', p: 2 }}>
            <Button
              variant="outlined"
              startIcon={<DownloadIcon />}
              onClick={exportData}
            >
              导出数据
            </Button>
          </CardActions>
        )}
      </Card>

      {/* 消息提示 */}
      <Snackbar
        open={!!error || !!successMessage}
        autoHideDuration={3000}
        onClose={() => { setError(null); setSuccessMessage(null); }}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert
          onClose={() => { setError(null); setSuccessMessage(null); }}
          severity={error ? 'error' : 'success'}
          sx={{ width: '100%' }}
        >
          {error || successMessage}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default FundHistoryPage;

// frontend/angular-app/src/app/features/fund-history/fund-history.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatSortModule, Sort } from '@angular/material/sort';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBarModule, MatSnackBar } from '@angular/material/snack-bar';
import { MatSelectModule } from '@angular/material/select';
import { MatOptionModule } from '@angular/material/core';
import { MatDividerModule } from '@angular/material/divider';
import { FundService, FundHistoryData } from '../../core/services/fund.service';
import { Observable } from 'rxjs';
import { ChartConfiguration, ChartData, ChartEvent, ChartType } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';

@Component({
  selector: 'app-fund-history',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatSelectModule,
    MatOptionModule,
    MatDividerModule
  ],
  templateUrl: './fund-history.component.html',
  styleUrls: ['./fund-history.component.scss']
})
export class FundHistoryComponent implements OnInit {
  // 表单控件
  historyForm: FormGroup;
  
  // 数据
  displayedColumns: string[] = ['date', 'nav', 'totalNav', 'dailyChange'];
  dataSource: FundHistoryData[] = [];
  filteredData: FundHistoryData[] = [];
  
  // 状态
  isLoading = false;
  isChartLoading = false;
  error: string | null = null;
  
  // 分页
  pageSize = 20;
  pageIndex = 0;
  totalItems = 0;
  
  // 排序
  sortOrder: 'asc' | 'desc' = 'desc';
  sortActive = 'date';
  
  // 图表相关
  @ViewChild(BaseChartDirective) chart?: BaseChartDirective;
  
  chartType: ChartType = 'line';
  chartDatasets: ChartConfiguration['data']['datasets'] = [];
  chartLabels: string[] = [];
  
  chartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top',
      },
      tooltip: {
        mode: 'index',
        intersect: false,
      },
    },
    scales: {
      x: {
        display: true,
        title: {
          display: true,
          text: '日期'
        }
      },
      y: {
        display: true,
        title: {
          display: true,
          text: '净值'
        }
      }
    }
  };
  
  // 图表类型选项
  chartTypes = [
    { value: 'line', label: '折线图' },
    { value: 'bar', label: '柱状图' }
  ];
  
  // 时间周期选项
  timePeriods = [
    { value: '7d', label: '最近7天' },
    { value: '1m', label: '最近1个月' },
    { value: '3m', label: '最近3个月' },
    { value: '6m', label: '最近6个月' },
    { value: '1y', label: '最近1年' },
    { value: '3y', label: '最近3年' },
    { value: '5y', label: '最近5年' },
    { value: 'custom', label: '自定义' }
  ];
  
  // 默认日期范围
  defaultStartDate: Date;
  defaultEndDate: Date;
  
  constructor(
    private fb: FormBuilder,
    private fundService: FundService,
    private snackBar: MatSnackBar
  ) {
    // 初始化日期范围（默认最近1年）
    this.defaultEndDate = new Date();
    this.defaultStartDate = new Date();
    this.defaultStartDate.setFullYear(this.defaultEndDate.getFullYear() - 1);
    
    // 初始化表单
    this.historyForm = this.fb.group({
      fundCode: ['110022', Validators.required],
      timePeriod: ['1y'],
      startDate: [this.defaultStartDate],
      endDate: [this.defaultEndDate]
    });
    
    // 监听时间周期变化，自动更新日期范围
    this.historyForm.get('timePeriod')?.valueChanges.subscribe(period => {
      this.updateDateRangeByPeriod(period);
    });
  }
  
  ngOnInit(): void {
    // 初始加载数据
    this.loadFundHistory();
  }
  
  /**
   * 根据时间周期更新日期范围
   */
  updateDateRangeByPeriod(period: string): void {
    const endDate = new Date();
    const startDate = new Date();
    
    switch (period) {
      case '7d':
        startDate.setDate(endDate.getDate() - 7);
        break;
      case '1m':
        startDate.setMonth(endDate.getMonth() - 1);
        break;
      case '3m':
        startDate.setMonth(endDate.getMonth() - 3);
        break;
      case '6m':
        startDate.setMonth(endDate.getMonth() - 6);
        break;
      case '1y':
        startDate.setFullYear(endDate.getFullYear() - 1);
        break;
      case '3y':
        startDate.setFullYear(endDate.getFullYear() - 3);
        break;
      case '5y':
        startDate.setFullYear(endDate.getFullYear() - 5);
        break;
      case 'custom':
        return; // 自定义范围，不自动更新
      default:
        startDate.setFullYear(endDate.getFullYear() - 1);
    }
    
    this.historyForm.patchValue({
      startDate,
      endDate
    });
  }
  
  /**
   * 加载基金历史数据
   */
  loadFundHistory(): void {
    if (!this.historyForm.valid) {
      return;
    }
    
    this.isLoading = true;
    this.isChartLoading = true;
    this.error = null;
    
    const fundCode = this.historyForm.get('fundCode')?.value;
    const startDate = this.historyForm.get('startDate')?.value;
    const endDate = this.historyForm.get('endDate')?.value;
    
    // 格式化日期
    const formattedStartDate = startDate?.toISOString().split('T')[0];
    const formattedEndDate = endDate?.toISOString().split('T')[0];
    
    this.fundService.getFundNavFromEastmoney(fundCode, 1, 1000, formattedStartDate, formattedEndDate)
      .subscribe({
        next: (data) => {
          this.dataSource = data;
          this.filteredData = [...data];
          this.totalItems = data.length;
          this.pageIndex = 0;
          this.sortData();
          this.updateChartData();
          this.isLoading = false;
          this.isChartLoading = false;
          this.snackBar.open(`成功加载基金${fundCode}的历史净值数据`, '关闭', { duration: 3000 });
        },
        error: (error) => {
          this.error = `获取基金历史数据失败: ${error.message}`;
          this.isLoading = false;
          this.isChartLoading = false;
          this.snackBar.open('获取基金历史数据失败', '关闭', { duration: 3000 });
        }
      });
  }
  
  /**
   * 更新图表数据
   */
  updateChartData(): void {
    if (this.dataSource.length === 0) {
      return;
    }
    
    // 排序数据（按日期升序）
    const sortedData = [...this.dataSource].sort((a, b) => 
      new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    
    // 准备图表数据
    this.chartLabels = sortedData.map(item => item.date);
    
    this.chartDatasets = [
      {
        data: sortedData.map(item => item.nav),
        label: '单位净值',
        borderColor: '#3f51b5',
        backgroundColor: 'rgba(63, 81, 181, 0.1)',
        fill: true,
        tension: 0.3,
        pointRadius: 2,
        pointHoverRadius: 5,
      },
      {
        data: sortedData.map(item => item.totalNav),
        label: '累计净值',
        borderColor: '#4caf50',
        backgroundColor: 'rgba(76, 175, 80, 0.1)',
        fill: true,
        tension: 0.3,
        pointRadius: 2,
        pointHoverRadius: 5,
      }
    ];
    
    // 更新图表
    this.chart?.update();
  }
  
  /**
   * 处理分页变化
   */
  handlePageEvent(event: PageEvent): void {
    this.pageSize = event.pageSize;
    this.pageIndex = event.pageIndex;
  }
  
  /**
   * 处理排序变化
   */
  handleSortChange(sort: Sort): void {
    if (sort.active && sort.direction) {
      this.sortActive = sort.active;
      this.sortOrder = sort.direction as 'asc' | 'desc';
      this.sortData();
    }
  }
  
  /**
   * 排序数据
   */
  sortData(): void {
    const data = [...this.dataSource];
    const isAsc = this.sortOrder === 'asc';
    
    this.filteredData = data.sort((a, b) => {
      switch (this.sortActive) {
        case 'date':
          return this.compare(new Date(a.date), new Date(b.date), isAsc);
        case 'nav':
          return this.compare(a.nav, b.nav, isAsc);
        case 'totalNav':
          return this.compare(a.totalNav, b.totalNav, isAsc);
        case 'dailyChange':
          return this.compare(a.dailyChange, b.dailyChange, isAsc);
        default:
          return 0;
      }
    });
  }
  
  /**
   * 比较函数
   */
  compare(a: number | Date, b: number | Date, isAsc: boolean): number {
    return (a < b ? -1 : 1) * (isAsc ? 1 : -1);
  }
  
  /**
   * 格式化涨跌幅
   */
  formatDailyChange(value: number): string {
    const sign = value > 0 ? '+' : '';
    return `${sign}${(value * 100).toFixed(2)}%`;
  }
  
  /**
   * 获取涨跌幅样式类
   */
  getDailyChangeClass(value: number): string {
    if (value > 0) return 'positive';
    if (value < 0) return 'negative';
    return 'neutral';
  }
  
  /**
   * 刷新数据
   */
  refreshData(): void {
    // 清除缓存
    const fundCode = this.historyForm.get('fundCode')?.value;
    this.fundService.clearNavDataCache(fundCode);
    // 重新加载数据
    this.loadFundHistory();
  }
  
  /**
   * 切换图表类型
   */
  changeChartType(type: ChartType): void {
    this.chartType = type;
    this.chart?.update();
  }
  
  /**
   * 导出数据
   */
  exportData(): void {
    if (this.dataSource.length === 0) {
      this.snackBar.open('没有数据可以导出', '关闭', { duration: 3000 });
      return;
    }
    
    // 生成CSV内容
    const headers = ['日期', '单位净值', '累计净值', '日涨跌幅(%)'];
    const rows = this.dataSource.map(item => [
      item.date,
      item.nav,
      item.totalNav,
      (item.dailyChange * 100).toFixed(2)
    ]);
    
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');
    
    // 创建下载链接
    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    
    link.setAttribute('href', url);
    link.setAttribute('download', `fund_history_${this.historyForm.get('fundCode')?.value}_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    this.snackBar.open('数据导出成功', '关闭', { duration: 3000 });
  }
}
<div class="fund-history-container">
  <!-- 页面标题 -->
  <h1 class="page-title">
    <mat-icon>show_chart</mat-icon>
    基金历史净值查询
  </h1>
  
  <!-- 查询表单 -->
  <mat-card class="search-card">
    <mat-card-content>
      <form [formGroup]="historyForm" class="search-form">
        <div class="form-row">
          <!-- 基金代码输入 -->
          <mat-form-field appearance="outline" class="form-field">
            <mat-label>基金代码</mat-label>
            <input matInput formControlName="fundCode" placeholder="请输入基金代码，例如：110022">
            <mat-icon matPrefix>account_balance</mat-icon>
            <mat-error *ngIf="historyForm.get('fundCode')?.hasError('required')">
              基金代码是必填项
            </mat-error>
          </mat-form-field>
          
          <!-- 时间周期选择 -->
          <mat-form-field appearance="outline" class="form-field">
            <mat-label>时间周期</mat-label>
            <mat-select formControlName="timePeriod">
              <mat-option *ngFor="let period of timePeriods" [value]="period.value">
                {{ period.label }}
              </mat-option>
            </mat-select>
            <mat-icon matPrefix>schedule</mat-icon>
          </mat-form-field>
        </div>
        
        <div class="form-row">
          <!-- 开始日期 -->
          <mat-form-field appearance="outline" class="form-field">
            <mat-label>开始日期</mat-label>
            <input matInput formControlName="startDate" [matDatepicker]="startDatePicker">
            <mat-datepicker-toggle matIconSuffix [for]="startDatePicker"></mat-datepicker-toggle>
            <mat-datepicker #startDatePicker></mat-datepicker>
          </mat-form-field>
          
          <!-- 结束日期 -->
          <mat-form-field appearance="outline" class="form-field">
            <mat-label>结束日期</mat-label>
            <input matInput formControlName="endDate" [matDatepicker]="endDatePicker">
            <mat-datepicker-toggle matIconSuffix [for]="endDatePicker"></mat-datepicker-toggle>
            <mat-datepicker #endDatePicker></mat-datepicker>
          </mat-form-field>
        </div>
        
        <!-- 操作按钮 -->
        <div class="form-actions">
          <button mat-raised-button color="primary" (click)="loadFundHistory()" [disabled]="isLoading">
            <mat-icon *ngIf="!isLoading">search</mat-icon>
            <mat-spinner *ngIf="isLoading" diameter="20"></mat-spinner>
            {{ isLoading ? '查询中...' : '查询' }}
          </button>
          
          <button mat-raised-button (click)="refreshData()" [disabled]="isLoading">
            <mat-icon>refresh</mat-icon>
            刷新
          </button>
          
          <button mat-raised-button (click)="exportData()" [disabled]="isLoading || dataSource.length === 0">
            <mat-icon>download</mat-icon>
            导出数据
          </button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
  
  <!-- 错误信息 -->
  <div *ngIf="error" class="error-message">
    <mat-icon>error_outline</mat-icon>
    <span>{{ error }}</span>
  </div>
  
  <!-- 数据表格 -->
  <mat-card class="data-card" *ngIf="!isLoading">
    <mat-card-header>
      <mat-card-title>
        <mat-icon>table_chart</mat-icon>
        基金历史净值数据
      </mat-card-title>
      <mat-card-subtitle *ngIf="dataSource.length > 0">
        共 {{ totalItems }} 条记录
      </mat-card-subtitle>
    </mat-card-header>
    
    <mat-card-content>
      <div class="table-container">
        <mat-table [dataSource]="filteredData.slice(pageIndex * pageSize, (pageIndex + 1) * pageSize)" matSort (matSortChange)="handleSortChange($event)">
          <!-- 日期列 -->
          <ng-container matColumnDef="date">
            <mat-header-cell *matHeaderCellDef mat-sort-header="date"> 日期 </mat-header-cell>
            <mat-cell *matCellDef="let element"> {{ element.date }} </mat-cell>
          </ng-container>
          
          <!-- 单位净值列 -->
          <ng-container matColumnDef="nav">
            <mat-header-cell *matHeaderCellDef mat-sort-header="nav"> 单位净值 </mat-header-cell>
            <mat-cell *matCellDef="let element"> {{ element.nav.toFixed(4) }} </mat-cell>
          </ng-container>
          
          <!-- 累计净值列 -->
          <ng-container matColumnDef="totalNav">
            <mat-header-cell *matHeaderCellDef mat-sort-header="totalNav"> 累计净值 </mat-header-cell>
            <mat-cell *matCellDef="let element"> {{ element.totalNav.toFixed(4) }} </mat-cell>
          </ng-container>
          
          <!-- 日涨跌幅列 -->
          <ng-container matColumnDef="dailyChange">
            <mat-header-cell *matHeaderCellDef mat-sort-header="dailyChange"> 日涨跌幅 </mat-header-cell>
            <mat-cell *matCellDef="let element" [class]="getDailyChangeClass(element.dailyChange)">
              {{ formatDailyChange(element.dailyChange) }}
            </mat-cell>
          </ng-container>
          
          <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
          <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
        </mat-table>
        
        <!-- 空数据状态 -->
        <div class="empty-state" *ngIf="filteredData.length === 0">
          <mat-icon>info_outline</mat-icon>
          <p>暂无数据，请尝试调整查询条件</p>
        </div>
        
        <!-- 加载状态 -->
        <div class="loading-overlay" *ngIf="isLoading">
          <mat-spinner diameter="40"></mat-spinner>
          <p>正在加载数据...</p>
        </div>
      </div>
    </mat-card-content>
    
    <!-- 分页控件 -->
    <mat-card-actions class="pagination-actions">
      <mat-paginator
        [length]="totalItems"
        [pageSize]="pageSize"
        [pageSizeOptions]="[10, 20, 50, 100]"
        [showFirstLastButtons]="true"
        (page)="handlePageEvent($event)"
        aria-label="选择页面"
      ></mat-paginator>
    </mat-card-actions>
  </mat-card>
  
  <!-- 数据可视化图表区域 -->
  <mat-card class="chart-card" *ngIf="!isLoading">
    <mat-card-header>
      <mat-card-title>
        <mat-icon>show_chart</mat-icon>
        净值走势图表
      </mat-card-title>
      <mat-card-subtitle>
        基金单位净值变化趋势
      </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <!-- 图表控制 -->
      <div class="chart-controls" *ngIf="dataSource.length > 0">
        <mat-chip-list class="chart-type-chips">
          <mat-chip
            *ngFor="let type of chartTypes"
            [selected]="chartType === type.value"
            (click)="changeChartType(type.value as ChartType)"
            color="primary"
            class="chart-type-chip">
            {{ type.label }}
          </mat-chip>
        </mat-chip-list>
      </div>
      
      <!-- 图表容器 -->
      <div class="chart-container" *ngIf="dataSource.length > 0">
        <canvas
          baseChart
          [data]="{ datasets: chartDatasets, labels: chartLabels }"
          [options]="chartOptions"
          [type]="chartType">
        </canvas>
        
        <!-- 加载状态 -->
        <div class="chart-loading" *ngIf="isChartLoading">
          <mat-spinner diameter="40"></mat-spinner>
          <p>正在绘制图表...</p>
        </div>
      </div>
      
      <!-- 空数据状态 -->
      <div class="chart-placeholder" *ngIf="dataSource.length === 0">
        <p>暂无数据，请先查询基金历史净值</p>
        <mat-icon class="chart-icon">insert_chart_outlined</mat-icon>
      </div>
    </mat-card-content>
  </mat-card>
  
  <!-- 加载状态 -->
  <div class="global-loading" *ngIf="isLoading">
    <mat-spinner diameter="60"></mat-spinner>
    <p>正在获取基金历史数据...</p>
  </div>
</div>
